language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t spedersen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true spedersen/docker-react npm run test